// <auto-generated />
using System;
using BookHouse.Models.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookHouse.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20200916064150_editDanhMuctable")]
    partial class editDanhMuctable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookHouse.Models.Entities.DanhMucSach", b =>
                {
                    b.Property<int>("DanhMucSachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(10000);

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("DanhMucSachId");

                    b.ToTable("DanhMucSachs");
                });

            modelBuilder.Entity("BookHouse.Models.Entities.Sach", b =>
                {
                    b.Property<int>("SachID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnhSach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<int?>("DanhMucSachId")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaSach")
                        .HasColumnType("decimal(18,2)")
                        .HasMaxLength(50000);

                    b.Property<string>("NXB")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime>("NgayXuatBan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("TenSach")
                        .HasColumnType("int")
                        .HasMaxLength(500);

                    b.Property<string>("TomTatSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(100000);

                    b.HasKey("SachID");

                    b.HasIndex("DanhMucSachId");

                    b.ToTable("Sachs");
                });

            modelBuilder.Entity("BookHouse.Models.Entities.Sach", b =>
                {
                    b.HasOne("BookHouse.Models.Entities.DanhMucSach", "DanhMucSach")
                        .WithMany("Sachs")
                        .HasForeignKey("DanhMucSachId");
                });
#pragma warning restore 612, 618
        }
    }
}
